name: Check Build

on:
  pull_request:
    branches:
      - main

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                node-version: [18, 22, 23]
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm ci

            - name: Lint
              run: |
               echo "Running Lint on ${{ matrix.os }} with Node.js ${{ matrix.node-version }}"
               npx eslint ./src --ignore-pattern "**/__tests__/**" --ignore-pattern "**\\__tests__\\**"

            - name: Test
              run: npm run test

            - name: Build
              run: |
               echo "Building on ${{ matrix.os }} with Node.js ${{ matrix.node-version }}"
               npm run build